import type { Database } from "@/types"

const now = new Date()
const daysAgo = (days: number) =>
  new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString()
const daysFromNow = (days: number) =>
  new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString().split("T")[0]

export const SEED_USER_IDS = {
  shipper: "seed-shipper-1",
  carrier: "seed-carrier-1",
  broker: "seed-broker-1",
  shipper2: "seed-shipper-2",
} as const

export function createSeedDatabase(): Database {
  return {
    session: null,
    users: [
      {
        id: SEED_USER_IDS.shipper,
        email: "shipper@demo.com",
        password: "demo123",
        name: "Ahmed Al-Rashid",
        companyName: "Baghdad Trading Co.",
        role: "shipper",
        verified: true,
        createdAt: daysAgo(30),
      },
      {
        id: SEED_USER_IDS.shipper2,
        email: "client@demo.com",
        password: "demo123",
        name: "Sara Hassan",
        companyName: "Basra Imports Ltd.",
        role: "shipper",
        verified: true,
        createdAt: daysAgo(20),
      },
      {
        id: SEED_USER_IDS.carrier,
        email: "carrier@demo.com",
        password: "demo123",
        name: "Omar Al-Taie",
        companyName: "Euphrates Transport",
        role: "carrier",
        verified: true,
        createdAt: daysAgo(25),
      },
      {
        id: SEED_USER_IDS.broker,
        email: "broker@demo.com",
        password: "demo123",
        name: "Khalid Mansour",
        companyName: "Iraq Freight Brokers",
        role: "broker",
        verified: true,
        createdAt: daysAgo(15),
      },
    ],
    trucks: [
      {
        id: "seed-truck-1",
        carrierId: SEED_USER_IDS.carrier,
        plateNumber: "BGD-4521",
        truckType: "flatbed",
        capacityKg: 25000,
        available: true,
        createdAt: daysAgo(20),
      },
      {
        id: "seed-truck-2",
        carrierId: SEED_USER_IDS.carrier,
        plateNumber: "BSR-8834",
        truckType: "refrigerated",
        capacityKg: 18000,
        available: true,
        createdAt: daysAgo(18),
      },
    ],
    loads: [
      {
        id: "seed-load-1",
        title: "Steel Beams - Baghdad to Basra",
        cargoType: "construction",
        pickupCity: "Baghdad",
        pickupGovernorate: "Baghdad",
        deliveryCity: "Basra",
        deliveryGovernorate: "Basra",
        weightKg: 22000,
        volumeM3: 45,
        truckType: "flatbed",
        pickupDate: daysFromNow(3),
        deliveryDeadline: daysFromNow(5),
        priceRangeMin: 800,
        priceRangeMax: 1200,
        description: "Heavy steel beams for construction project. Requires flatbed with straps.",
        status: "pending_offers",
        shipperId: SEED_USER_IDS.shipper,
        createdAt: daysAgo(2),
      },
      {
        id: "seed-load-2",
        title: "Refrigerated Food - Erbil to Mosul",
        cargoType: "food",
        pickupCity: "Erbil",
        pickupGovernorate: "Erbil",
        deliveryCity: "Mosul",
        deliveryGovernorate: "Nineveh",
        weightKg: 12000,
        truckType: "refrigerated",
        pickupDate: daysFromNow(1),
        deliveryDeadline: daysFromNow(2),
        priceRangeMin: 500,
        priceRangeMax: 700,
        description: "Perishable food items. Temperature controlled required.",
        status: "published",
        shipperId: SEED_USER_IDS.shipper2,
        brokerId: SEED_USER_IDS.broker,
        createdAt: daysAgo(1),
      },
      {
        id: "seed-load-3",
        title: "Electronics - Baghdad to Najaf",
        cargoType: "electronics",
        pickupCity: "Baghdad",
        pickupGovernorate: "Baghdad",
        deliveryCity: "Najaf",
        deliveryGovernorate: "Najaf",
        weightKg: 5000,
        truckType: "box truck",
        pickupDate: daysFromNow(5),
        priceRangeMin: 350,
        priceRangeMax: 500,
        status: "assigned",
        shipperId: SEED_USER_IDS.shipper,
        assignedCarrierId: SEED_USER_IDS.carrier,
        createdAt: daysAgo(5),
      },
      {
        id: "seed-load-4",
        title: "Fuel Tanker - Kirkuk to Baghdad",
        cargoType: "fuel",
        pickupCity: "Kirkuk",
        pickupGovernorate: "Kirkuk",
        deliveryCity: "Baghdad",
        deliveryGovernorate: "Baghdad",
        weightKg: 30000,
        truckType: "tanker",
        pickupDate: daysFromNow(2),
        priceRangeMin: 900,
        priceRangeMax: 1100,
        status: "in_transit",
        shipperId: SEED_USER_IDS.shipper2,
        brokerId: SEED_USER_IDS.broker,
        assignedCarrierId: SEED_USER_IDS.carrier,
        createdAt: daysAgo(7),
      },
      {
        id: "seed-load-5",
        title: "General Cargo - Basra to Karbala",
        cargoType: "general",
        pickupCity: "Basra",
        pickupGovernorate: "Basra",
        deliveryCity: "Karbala",
        deliveryGovernorate: "Karbala",
        weightKg: 8000,
        truckType: "box truck",
        pickupDate: daysFromNow(7),
        priceRangeMin: 400,
        priceRangeMax: 600,
        status: "published",
        shipperId: SEED_USER_IDS.shipper,
        createdAt: daysAgo(0),
      },
      {
        id: "seed-load-6",
        title: "Construction Materials - Mosul to Erbil",
        cargoType: "construction",
        pickupCity: "Mosul",
        pickupGovernorate: "Nineveh",
        deliveryCity: "Erbil",
        deliveryGovernorate: "Erbil",
        weightKg: 15000,
        truckType: "lowboy",
        pickupDate: daysFromNow(4),
        priceRangeMin: 600,
        priceRangeMax: 850,
        status: "delivered",
        shipperId: SEED_USER_IDS.shipper2,
        brokerId: SEED_USER_IDS.broker,
        assignedCarrierId: SEED_USER_IDS.carrier,
        createdAt: daysAgo(14),
      },
    ],
    offers: [
      {
        id: "seed-offer-1",
        loadId: "seed-load-1",
        carrierId: SEED_USER_IDS.carrier,
        truckId: "seed-truck-1",
        price: 950,
        message: "Available with experienced driver. Can load within 24 hours.",
        status: "pending",
        createdAt: daysAgo(1),
      },
      {
        id: "seed-offer-2",
        loadId: "seed-load-3",
        carrierId: SEED_USER_IDS.carrier,
        truckId: "seed-truck-2",
        price: 420,
        status: "accepted",
        createdAt: daysAgo(4),
      },
      {
        id: "seed-offer-3",
        loadId: "seed-load-4",
        carrierId: SEED_USER_IDS.carrier,
        truckId: "seed-truck-1",
        price: 1000,
        status: "accepted",
        createdAt: daysAgo(6),
      },
      {
        id: "seed-offer-4",
        loadId: "seed-load-6",
        carrierId: SEED_USER_IDS.carrier,
        truckId: "seed-truck-1",
        price: 720,
        status: "accepted",
        createdAt: daysAgo(12),
      },
    ],
    notifications: [
      {
        id: "seed-notif-1",
        userId: SEED_USER_IDS.shipper,
        type: "offer_received",
        message: "New offer received on Steel Beams - Baghdad to Basra",
        loadId: "seed-load-1",
        offerId: "seed-offer-1",
        read: false,
        createdAt: daysAgo(1),
      },
    ],
  }
}

export const DEMO_ACCOUNTS = [
  { email: "shipper@demo.com", password: "demo123", role: "shipper" as const },
  { email: "carrier@demo.com", password: "demo123", role: "carrier" as const },
  { email: "broker@demo.com", password: "demo123", role: "broker" as const },
]
